# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, valueswir
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

minimal_mistakes_skin: "dark_cgg" #"air_cgg"

# Site Settings
locale: "en"
title: " "
masthead_title: "CarlosGG's Homepage"
name: Carlos Alberto Gomez Gonzalez
description: >- # this means to ignore newlines until "baseurl:"
  Carlos Alberto Gomez Gonzalez's personal website.
baseurl:  # the subpath of your site, e.g. "/blog"
url: https://carlos-gg.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
repository: carlos-gg/carlos-gg.github.io  # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
github_username: carlos-gg
teaser: "/assets/images/bio-photo.jpg"
search: false

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-84473187-2



# Site Author
author:
  name             : "Carlos A. Gomez Gonzalez"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "Lead Data Scientist"
  email            : carlosgg33@gmail.com
  uri              : #"https://carlos-gg.github.io"
  location         : "Barcelona, Spain"
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : carlos-gg
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : 
  lastfm           :
  linkedin         : carlosgog
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
  - jemoji


collections:
  research:
    output: true
    permalink: /:collection/:path/

defaults:
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: #true
      comments: #true
      share: #true
      related: true
      header:
        title:
        overlay_image: /assets/images/header_image_geo.jpg
        overlay_filter: 0.0
